### PR TITLE
N&N for quick assist to rename constants to standard naming

### PR DESCRIPTION
**Pull request by jjohnstn**
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/751

### CODE REVIEW

**Comment by jjohnstn** [comment]
@vogella Thanks for reviewing the other N&N.  Can you review this one too?

**Comment by vogella** [comment]
Looks great, very nice functionality.

**Comment by jjohnstn** [comment]
Thanks @vogella

**Comment by vogella** [comment]
Thanks for keeping JDT UI alive.

**Pull request merged**
