### PR TITLE
Remove Plugins used for experimentation #99

### PR DESCRIPTION
**Pull request by jukzi**
There is no replacement but that stuff seems to be unused for decades.
This PR includes 6 commits for: 

- org.eclipse.core.filesystem.ftp
- org.eclipse.ui.examples.statushandlers.testtool
- org.eclipse.ui.examples.splash.blame_1.0.0.jar
- org.eclipse.help.tocviewer*.jar
- org.eclipse.ui.ide.examples.markers
- org.eclipse.ui.ide.examples.projectsnapshot

### CODE REVIEW

**Comment by akurtakov** [comment]
So these are on the web page  but not linked from anywhere actually ?

**Comment by jukzi** [comment]
I have not found any reference to it. i doubt they are on any web page.

**Comment by akurtakov** [comment]
This is supposed to be autodeployed on the web page somewhere but it is a mystery to me why code was put on the web page at all.

**Comment by jukzi** [comment]
google doesn't find those anywhere

**Comment by jukzi** [comment]
Well if somebody knows where to find it he could indeed access it from Webpage using the absolute path
for example:
https://eclipse.dev/eclipse/platform-core/plugins/org.eclipse.core.filesystem.ftp/.classpath

**Comment by akurtakov** [comment]
OMG https://eclipse.dev/eclipse/platform-ui/ the whole page is irrelevant and I guess a good chunk of the content in this repo. 
I'm stepping back here as the content looks clearly useless but I have a feeling I'm missing smth with the web pages . Aka I can't spend more time and whoever does the work decides.

**Comment by jukzi** [comment]
@vogella any idea how much can be removed?

**Comment by jukzi** [comment]
it starts at https://eclipse.dev/eclipse/ which is linked from https://projects.eclipse.org/projects/eclipse

**Comment by jukzi** [comment]
If there is no objection i will submit this. It's totally wrong to publish unmaintained code to the web

**Comment by vogella** [comment]
Fine to remove for me, IIRC @ptziegler did migrate one example to platform UI a while ago. 

Removal is fine for you @ptziegler?

**Comment by ptziegler** [comment]
> Fine to remove for me, IIRC @ptziegler did migrate one example to platform UI a while ago.
> 
> Removal is fine for you @ptziegler?

Fine by me. We were only interested in [org.eclipse.ui.examples.filesystems](https://github.com/eclipse-platform/eclipse.platform/tree/master/resources/examples/org.eclipse.ui.examples.filesystem) example, because of the in-memory implementation of a project. But as you can see, it was already moved to the eclipse.platform project. 😄

**Comment by ptziegler** [comment]
As as side note, those examples used to be featured in some Eclipse magazines 10-or-so years ago. Which is probably why they ended up on the webpage in the first place.

**Pull request merged**
