### PR TITLE
Add N&N for Javadoc styling improvements

### PR DESCRIPTION
**Pull request by RedeemerSK**
PR: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1074
Fixes: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1073

### CODE REVIEW

**Review by jjohnstn — CHANGES_REQUESTED** [review]
Hi @RedeemerSK thanks for the N&N.  There is a problem with the text not referring to the 
javadoc_styling_new.png image (New is upper-case in the text).  I did a few very minor text edits locally to make it read a little clearer.  If you are interested, the edited text is below or you can just fix the image issue if you prefer the original.

  <tr id="javadocStylingImprovements">
    
    <td class="title">Javadoc styling improvements</td>
    <td class="content">
      Styling of the method signatures displayed in the Javadoc view and hover dialog has been improved to make them easier
      to read.
      <p>
      Until now, the entire signature has been rendered as one continuous text making it a bit hard to identify specific parts.
      This is especially difficult when the signature contained type variables of generic declarations:
      </p>
      <p>Old Javadoc styling</p>
      Now, by default, parts of the signature are visually distinguished by using italic, lighter, or colorized text or by placing
      them on separate lines.
      <p>New Javadoc styling</p>
      <p>
      Coloring is used to distinguish different types used as type variables. Four different colors are pre-configured and are also
      re-used repeatedly in case more unique types are present in displayed Javadoc.  Note: custom colors can be configured to
      avoid this repetition.
      </p>
      <p>
      All aspects of the new styling can be customized through the Javadoc styling menu accessible via a new menu button added to
      the toolbar of the Javadoc view and Javadoc hover (here visible after pressing F2), where the button itself toggles the new styling
      functionality on/off.
      </p>
      <p>New Javadoc styling menu</p>
    </td>
  </tr>

**Comment by RedeemerSK** [comment]
Thank you @jjohnstn for the fixes, I'm OK with you version. Please feel free to commit. Thank you

**Comment by merks** [comment]
This looks really cool. I’m totally looking forward to having this available. 🎉

**Comment by RedeemerSK** [comment]
> This looks really cool. I’m totally looking forward to having this available. 🎉

If only Eclipse on Windows would not be using legacy Internet Explorer browser (SWT) backend, because then newer CSS selectors could be used making it possible to implement some cool UI/UX tricks - e.g. "highlighting" occurrences of the same class in entire signature (highlighting = everything but occurrences gets lower opacity making occurrences to "stand out") ... which I kind of had working when I was prototyping styling enhancements but had to abandon it to conform to lowest denominator browser backend.

**Comment by jjohnstn** [comment]
@RedeemerSK i was unable to modify your patch so I made a new PR with all the changes.  @akurtakov Could you please close this when you merge my PR?

**Comment by akurtakov** [comment]
Pushed via https://github.com/eclipse-platform/www.eclipse.org-eclipse/commit/3c15248be6654007d1241fe91439234c88573134

**Pull request closed without merging**
