### PR TITLE
Merge news

### PR DESCRIPTION
**Pull request by laeubi**
Please check if this is sufficent!

An alternative would be to use a submodule for the `news` folder ...

### CODE REVIEW

**Review by mickaelistria — APPROVED** [review]
Definitely an improvement!
By putting news in this repo, the webstite is cleaner and leaner. Having thos contents closer to each other will more easily allow contributor to feel empoweredin also updating the website in general.

**Comment by iloveeclipse** [comment]
There is a problem with ECA validation of `Anonymous (manpalat@****.****.com)` account
@mpalat : any idea why?

image

**Comment by mickaelistria** [comment]
I suspect a different mail address was use sometimes in the past. However, the ECA check is more an indication, we can merge even if it complains if we can ensure the failures of the check are still valid contributions. As @mpalat has been a committer for a while, we can ignore this erroneous report, whichever is the cause.

**Comment by iloveeclipse** [comment]
Beside the failing ECA check I have no other objections.

**Comment by merks** [comment]
I had ECA problems like this merging XSD into EMF with XSD's very long history.  We just merged anyway, but I think I asked @waynebeaton whether that was okay...

**Review by jonahgraham — APPROVED** [review]
Please proceed - until this is merged there are broken links all over the place. https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3358#note_1168040

**Comment by jonahgraham** [comment]
I think you can't merge this PR in Github UI as both squash and rebase will break history. The push needs to be done directly IIRC.

The failing ECA checks relate to commits that are *already* in an Eclipse Platform repo, the ECA tool is not designed to check 20+ years of historical commit records.

**Comment by mickaelistria** [comment]
@laeubi no need for a PL to change repo settings, just push directly to master from CLI (I can do it if you want)
```
$ git fetch laeubi merge-news
$ git push eclipse FETCH_HEAD:master
```

**Comment by merks** [comment]
> @laeubi no need for a PL to change repo settings, just push directly to master from CLI (I can do it if you want)
> 
> ```
> $ git fetch laeubi merge-news
> $ git push eclipse FETCH_HEAD:master
> ```

@mickaelistria 

Doesn't the first choice need to be enabled?

image

**Comment by iloveeclipse** [comment]
I can enable merge if needed.

**Comment by iloveeclipse** [comment]
> @iloveeclipse Let's assume it's necessary and do that so we can for sure move forward. Of course we should disable it again afterwards.

You should be able to merge now.

**Comment by akurtakov** [comment]
Merged and disabled merge commits again to prevent other accidental merge commits.

**Comment by merks** [comment]
I'm not sure how long it takes the website to update so that this would work again:

https://eclipse.dev/eclipse/news/

**Comment by jonahgraham** [comment]
Thanks all for resolving this quickly. I am now following up in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3358#note_1172779 as the news still hasn't appeared on the website.

@laeubi are you able to close off the "old" new git repo so that people don't push to there anymore. For other repos that were merged together we didn't archive the repo, but as there are no branches on the news repo, perhaps fully archiving it (After updating README) is a good thing to do.

**Comment by mickaelistria** [comment]
> Doesn't the first choice need to be enabled?

No. What you see here is GitHub UI, but GitHub is still Git and committers can still push manually whatever the UI settings are.

**Comment by iloveeclipse** [comment]
> @laeubi are you able to close off the "old" news git repo so that people don't push to there anymore.

@laeubi : please delete everything and leave default readme pointing to the new repo.

**Pull request merged**
