### PR TITLE
Add N&N about removal of unnecessary attributes in Features and Products

### PR DESCRIPTION
**Pull request by HannesWell**
Entries for
- https://github.com/eclipse-pde/eclipse.pde/issues/730
- https://github.com/eclipse-pde/eclipse.pde/pull/770
- https://github.com/eclipse-equinox/p2/pull/378
- https://github.com/eclipse-pde/eclipse.pde/pull/882

### CODE REVIEW

**Review by merks — COMMENTED** [review]
The name of the Feature-editor in the UI is Feature Manifest Editor and the name of the Product-editor in the UI is Product Configuration Editor.  it's probably better to use the actual names as seen in the Open With menue.

**Comment by HannesWell** [comment]
> The name of the Feature-editor in the UI is Feature Manifest Editor and the name of the Product-editor in the UI is Product Configuration Editor. it's probably better to use the actual names as seen in the Open With menue.

Thanks Ed, I updated the name from Product-editor to `Product Configuration` Editor.
But I have to admit that Feature Manifest Editor has IMHO the potential to confuse people and I would like to keep that as it is.
Maybe it would be better to change the 'official' name to only Feature Editor?

**Review by merks — APPROVED** [review]
Yes, it's a terrible name for the feature editor and would be better changed.  Even the product editor's name is kind of pointlessly unwieldy...

In any case, it looks better without they hyphenated names.

**Comment by HannesWell** [comment]
> Yes, it's a terrible name for the feature editor and would be better changed. Even the product editor's name is kind of pointlessly unwieldy...

Absolutely, that's something to change for the spring release. :)

Thanks again for your input.

**Pull request merged**
