### PR TITLE
Remove blank N&N isv documentation and the link to it

### PR DESCRIPTION
**Pull request by merks**
@MohananRahul  @noopur2507 

I don't think it's happened before that an entire page is effectively blank.  

The PR removes the empty isv docu page and the references to it.

Maybe there's a different way to handle that?

### CODE REVIEW

**Review by noopur2507 — APPROVED** [review]

**Comment by noopur2507** [comment]
Removing the page and its references seems fine in this case.

**Comment by HeikoKlare** [comment]
Sorry for being so late with the N&N, but we have #171 pending, which adds something to the ISV page.

**Comment by noopur2507** [comment]
> Sorry for being so late with the N&N, but we have #171 pending, which adds something to the ISV page.

I have reverted this PR via https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/176.

**Comment by merks** [comment]
@HeikoKlare 

At some point very soon folks start copying docs into the doc plugin, so you can't wait till the last minute.

Please consider to comment out empty sections as I've done recently.

**Comment by HeikoKlare** [comment]
> At some point very soon folks start copying docs into the doc plugin, so you can't wait till the last minute.
> 
> Please consider to comment out empty sections as I've done recently.

Thank you for the hint and sorry for being late with this. As mentioned in https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/171#issuecomment-2133158594, I was not properly aware of the timeline and expected us to have some more days for this.

I have commented out the empty sections in #171, so that the ISV page should be fine when having that merged.

**Pull request merged**
